apiVersion: apps/v1
kind: Deployment
metadata:
  name: demosite
  labels:
    name: demosite
    app: demo-site
spec:
  replicas: 1
  selector:
    matchLabels:
      name: demosite
      app: demo-site
    
  template:
    metadata:
      name: demosite
      labels:
        name: demosite
        app: demo-site
    spec:
      containers:
        - name: demo-site
          image: reg01kalyan.azurecr.io/demosite:latest   # add this to next line- imagepullpolicy: Always
          ports:
            - containerPort: 80
