apiVersion: apps/v1
kind: Deployment
metadata:
  name: demosite-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demosite
  template:
    metadata:
      labels:
        app: demosite
    spec:
      containers:
      - name: demosite
        image: kalyanproject.azurecr.io/project-abc:latest
        ports:
        - containerPort: 80
