apiVersion: apps/v1
kind: Deployment
metadata:
  name: demosite-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demosite
  template:
    metadata:
      labels:
        app: demosite
    spec:
      containers:
      - name: demo-site-container
        image: reg01kalyan.azurecr.io/demosite:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: LoadBalancer
  selector:
    app: example
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80